service: slackbot-pending-reviews
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}

package:
  include:
    - src/handler.js

functions:
  notify-pending-reviews:
    handler: src/handler.notifyPendingReviews
    name: notify-pending-reviews-${env:STAGE}
    description: 'Send a Slack message listing all GitHub pending reviews per team.'
    memorySize: 128
    timeout: 120
    events:
      - schedule: ${env:AWS_LAMBDA_SCHEDULE}

custom:
  dotenv:
    exclude:
      - AWS_REGION
